### PR TITLE
fix build on ubuntu 16.04 (use cmake c++11 directive)

### PR DESCRIPTION
**Pull request by ra1nb0w**
avoid the following error

In file included from /usr/include/c++/5/chrono:35:0,
from /home/user/tmp/dsdcc/timeutil.h:17,
from /home/user/tmp/dsdcc/dsd_decoder.cpp:19:
/usr/include/c++/5/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support must be enabled with the -std=c++11 or -std=gnu++11 compiler options.

### CODE REVIEW

**Comment by ra1nb0w** [comment]
thank you!
