### ISSUE TITLE
cygwin M_PI make error

### ISSUE THREAD

**Issue by nokiaman2002** [f4exb/dsdcc#65]
Trying to compile in cygwin 2.934 and receive the following error below. I am also unable to find dsdcc-1.9.5-X-src.tar.xz as mentioned in the https://github.com/fd00/yacp/blob/master/dsdcc/README.

$ make
[  3%] Building CXX object CMakeFiles/dsdcc.dir/descramble.cpp.o
[  6%] Building CXX object CMakeFiles/dsdcc.dir/dmr.cpp.o
[  9%] Building CXX object CMakeFiles/dsdcc.dir/dsd_decoder.cpp.o
[ 12%] Building CXX object CMakeFiles/dsdcc.dir/dsd_filters.cpp.o
/cygdrive/c/users/nokia/Desktop/dsdcc-bp/dsd_filters.cpp: In member function ‘short int DSDcc::DSDSecondOrderRecursiveFilter::run(short int)’:
/cygdrive/c/users/nokia/Desktop/dsdcc-bp/dsd_filters.cpp:230:74: error: ‘M_PI’ was not declared in this scope
  230 |         m_v[0] = ((1.0f - m_r) * (float) sample) + (2.0f * m_r * cos(2.0*M_PI*m_frequencyRatio) * m_v[1]) - (m_r * m_r * m_v[2]);
      |                                                                          ^~~~
make[2]: *** [CMakeFiles/dsdcc.dir/build.make:118: CMakeFiles/dsdcc.dir/dsd_filters.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:85: CMakeFiles/dsdcc.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
